- name: Creating The k3s Template in Proxmox
  hosts: proxmox_server
  gather_facts: false
  vars_files:
    - ../vars/template_vars.yaml
  tasks:

    - name: Include vault secrets
      ansible.builtin.include_vars:
        file: '../vars/secrets.yaml'
      no_log: true

    - name: Copy user-data to Proxmox node
      ansible.builtin.template:
        src: "../files/{{ user_data_file }}"
        remote_src: false
        dest: "{{ snippets_storage }}/user-data.yaml"
        owner: root
        group: root
        mode: '0644'
