- name: Setup vms and Install k3s etc
  hosts: cluster
  gather_facts: false
  tasks:

    - name: Download K3s install script
      ansible.builtin.uri:
        url: https://get.k3s.io
        return_content: true
      register: k3s_install_script
      delegate_to: node_0

    - name: Run the K3s install script
      ansible.builtin.shell: /bin/bash -s
      args:
        stdin: "{{ k3s_install_script.content }}"
        executable: /bin/bash
        creates: /var/lib/rancher/k3s
      register: install_server_node
      delegate_to: node_0

    - name: Wait for server token to be created
      ansible.builtin.wait_for:
        path: /var/lib/rancher/k3s/server/node-token
        state: present
        timeout: 60
      become: true
      delegate_to: node_0

    - name: Read k3s server token
      ansible.builtin.slurp:
        src: /var/lib/rancher/k3s/server/node-token
      register: k3s_token_raw
      become: true
      no_log: true
      delegate_to: node_0

    - name: Run the K3s install script as an agent
      ansible.builtin.shell: |
        K3S_URL=https://{{ hostvars[ansible_play_hosts[0]].ansible_host }}:6443 K3S_TOKEN={{ k3s_token_raw.content | b64decode | trim }} sh -
      args:
        stdin: "{{ k3s_install_script.content }}"
        executable: /bin/sh
        creates: /var/lib/rancher/k3s
      register: install_agent_node
      when: inventory_hostname != ansible_play_hosts[0]
      failed_when: install_agent_node.rc != 0
      delegate_to: "{{ inventory_hostname }}"
